"""Routes for the SPA dashboard at /web/index.html.

Three endpoints:
  GET /api/desk/data   → JSON MA_DATA snapshot (programmatic + client refresh)
  GET /web/data.js     → JS that sets `window.MA_DATA = {...}` (drop-in for SPA)
  GET /web/...         → static files served by the StaticFiles mount in api/main.py

The SPA's `<script src="data.js">` resolves relative to /web/index.html, so
hitting /web/data.js gets the dynamic JS — no SPA changes needed.

Old dashboard routes (/positioning, /dev, /tactical, /terminal, /guide)
are 307-redirected to /web/index.html in api/main.py to preserve external
links; the SPA's internal tabs replace those view-specific pages.
"""

from __future__ import annotations

import json

from fastapi import APIRouter
from fastapi.responses import JSONResponse, Response

from macro_positioning.dashboard.desk_data import build_desk_snapshot


router = APIRouter()


@router.get("/api/desk/data")
def desk_data_json() -> JSONResponse:
    """JSON snapshot of the entire MA_DATA contract."""
    return JSONResponse(content=build_desk_snapshot())


@router.get("/web/data.js")
def desk_data_js() -> Response:
    """Dynamic JS module that sets `window.MA_DATA = {...}`.

    Returned with text/javascript content-type and no-cache so the SPA
    always sees the latest snapshot on reload. Production should add
    a short-TTL cache once data is busy enough to need it.
    """
    snap = build_desk_snapshot()
    body = (
        "// Auto-generated by macro-analyzer (dashboard/desk_routes.py).\n"
        "// Mocks live in data.mock.js for offline/dev fallback.\n"
        f"window.MA_DATA = {json.dumps(snap, default=str)};\n"
    )
    return Response(
        content=body,
        media_type="application/javascript",
        headers={"Cache-Control": "no-cache, no-store, must-revalidate"},
    )
