// Mock data for Macro Analyzer dashboard.
// Reflects the v3 thesis (capital rotation through hyper-liquidity cycle)
// + trading framework regime model.
//
// Load order in production: this file loads BEFORE /web/data.js. The
// real snapshot from desk_routes.py overrides keys it provides; keys
// it doesn't yet emit (concepts, plans, streams, funnelConversion)
// fall through to the mock baseline below so the SPA still renders.

(function () {
const _MA_MOCK = {
  // ---------- Regime ----------
  regime: {
    framework: {
      label: "Commodity-Led Inflation",
      slug: "commodity_led_inflation",
      confidence: 0.78,
      bias: "real_asset_bullish",
      sizingModifier: 1.1,
      scoreModifier: 8,
      sinceDays: 14,
    },
    thesis: {
      label: "Two-Speed · Liquidity ↔ Structural",
      narrative:
        "Liquidity setting the pace, structural energy / resource stress setting leadership. Capital rotating from index beta into real assets faster than fundamentals are repaired.",
      version: "v3",
      author: "Lindsey",
      lastRevised: "2026-04-22",
    },
    // 90-day daily regime confidence trace (0..1) — for sparkline shape
    confidenceTrace: [0.41,0.43,0.42,0.45,0.49,0.52,0.50,0.48,0.51,0.55,0.58,0.62,0.60,0.58,0.61,0.65,0.68,0.66,0.64,0.66,0.69,0.71,0.70,0.67,0.69,0.72,0.74,0.73,0.71,0.74,0.76,0.78,0.76,0.74,0.77,0.79,0.81,0.79,0.77,0.79,0.81,0.82,0.80,0.78,0.80,0.82,0.83,0.81,0.79,0.80,0.82,0.83,0.81,0.78,0.79,0.81,0.83,0.81,0.79,0.80,0.81,0.83,0.82,0.80,0.79,0.81,0.83,0.82,0.80,0.78,0.77,0.79,0.80,0.78,0.76,0.77,0.78,0.78,0.77,0.78,0.79,0.78,0.77,0.78],
    // Dates per confidenceTrace index. Real /api/desk emits ISO dates;
    // mock computes them relative to a fixed "today" so the preview
    // renders realistic axis labels.
    confidenceTraceDates: (() => {
      const out = []; const today = new Date("2026-08-02");
      for (let i = 83; i >= 0; i--) {
        const d = new Date(today); d.setDate(d.getDate() - i);
        out.push(d.toISOString().slice(0, 10));
      }
      return out;
    })(),
    transitions: [
      { date: "2026-06-08", from: "Transitional Chop",  to: "Risk-On Expansion" },
      { date: "2026-07-06", from: "Risk-On Expansion", to: "Commodity-Led Inflation" },
    ],
  },

  // ---------- KPI strip ----------
  kpis: {
    cashPosture: { label: "Neutral", pct: 32, delta: -4 },
    activeTrades: { count: 6, exposureUsd: 184500 },
    pnlToday: { usd: 3120, pct: 1.69 },
    pnlWeek: { usd: 8450, pct: 4.58 },
    signalsHigh: { count: 4, deltaVsYesterday: +1 }, // score >= 75
    spendToday: { usd: 4.82, capUsd: 25 },
  },

  // ---------- Hero signals (top scored setups today) ----------
  heroSignals: [
    {
      id: "sig-ura-2605",
      asset: "URA",
      name: "Sprott Uranium Miners",
      side: "LONG",
      score: 88,
      scorePrev: 74,
      tier: 1,
      setup: "Long Base Accumulation · Breakout retest",
      regimeFit: "commodity_led_inflation",
      entry: 41.20,
      stop: 39.40,
      target: 47.50,
      rr: 3.50,
      whyNow: [
        "Reactor restart cadence accelerating; physical U₃O₈ tape firming above $94.",
        "Group reclaimed 50DMA on volume; relative strength leader vs SPY (+6.4% 20d).",
        "Aligns with framework regime: real-asset bias + liquidity neutral-to-easing.",
      ],
      sources: ["Doomberg", "Doomberg Substack", "FRED · CPI exp.", "Capitalist Exploits"],
      lastUpdate: "08:14",
    },
    {
      id: "sig-gld-2605",
      asset: "GLD",
      name: "SPDR Gold Trust",
      side: "LONG",
      score: 84,
      scorePrev: 81,
      tier: 1,
      setup: "Pullback to 50DMA · Demand reaction",
      regimeFit: "commodity_led_inflation",
      entry: 268.40,
      stop: 261.00,
      target: 296.00,
      rr: 3.73,
      whyNow: [
        "Real yields rolled over -18bps in 2 sessions; central-bank tape printed +47t May.",
        "Pullback held 50DMA on contracting volume — textbook constructive pullback.",
        "Debasement / hard-asset thesis intact; positioning still under Q4'25 peak.",
      ],
      sources: ["Doomberg", "FRED · DGS10", "Goldman GIR (S)"],
      lastUpdate: "08:11",
    },
    {
      id: "sig-xop-2605",
      asset: "XOP",
      name: "Oil & Gas E&P",
      side: "LONG",
      score: 78,
      scorePrev: 70,
      tier: 2,
      setup: "Breakout continuation",
      regimeFit: "commodity_led_inflation",
      entry: 152.10,
      stop: 147.00,
      target: 168.00,
      rr: 3.12,
      whyNow: [
        "Brent reclaimed $86 after Strait headlines; OVX deflating into the move.",
        "Sector breadth (XLE adv/dec) at 28d high; capex tape supportive.",
        "Cluster vote: 3/4 energy theses bullish, 1 mixed.",
      ],
      sources: ["Energy Cap.", "Reuters", "FRED · WTI"],
      lastUpdate: "08:09",
    },
    {
      id: "sig-tlt-2605",
      asset: "TLT",
      name: "20Y+ Treasury",
      side: "SHORT",
      score: 72,
      scorePrev: 76,
      tier: 2,
      setup: "Lower-high · failed reclaim",
      regimeFit: "commodity_led_inflation",
      entry: 86.40,
      stop: 88.20,
      target: 81.50,
      rr: 2.72,
      whyNow: [
        "Failed to reclaim 50DMA; lower high vs April. Inflation tape sticky.",
        "Term premium expanding; supply schedule front-loaded into Q3.",
      ],
      sources: ["FRED · DGS30", "Bianco (S)"],
      lastUpdate: "07:58",
    },
    {
      id: "sig-btc-2605",
      asset: "BTC",
      name: "Bitcoin",
      side: "WATCH",
      score: 68,
      scorePrev: 62,
      tier: 3,
      setup: "Probe · waiting on liquidity confirm",
      regimeFit: "monetary_debasement_hard_asset",
      entry: 71200,
      stop: 67800,
      target: 84000,
      rr: 3.76,
      whyNow: [
        "Holding above 200DMA but no decisive reclaim of prior range high.",
        "Stablecoin liquidity flat 4w; needs liquidity confirm before sizing.",
      ],
      sources: ["Doomberg", "Glassnode"],
      lastUpdate: "07:52",
    },
  ],

  // ---------- Watchlist (full scored) ----------
  watchlist: [
    { asset: "URA",  side: "LONG",  score: 88, dScore: +14, tier: 1, regime: "fit",  tech: "A",  vol: "A",  rr: 3.50, last: "08:14" },
    { asset: "GLD",  side: "LONG",  score: 84, dScore: +3,  tier: 1, regime: "fit",  tech: "A",  vol: "B+", rr: 3.73, last: "08:11" },
    { asset: "XOP",  side: "LONG",  score: 78, dScore: +8,  tier: 2, regime: "fit",  tech: "B+", vol: "A",  rr: 3.12, last: "08:09" },
    { asset: "TLT",  side: "SHORT", score: 72, dScore: -4,  tier: 2, regime: "fit",  tech: "B",  vol: "B",  rr: 2.72, last: "07:58" },
    { asset: "BTC",  side: "WATCH", score: 68, dScore: +6,  tier: 3, regime: "mix",  tech: "B",  vol: "C",  rr: 3.76, last: "07:52" },
    { asset: "DBA",  side: "WATCH", score: 65, dScore: +2,  tier: 3, regime: "fit",  tech: "B-", vol: "B",  rr: 2.40, last: "07:46" },
    { asset: "ITA",  side: "LONG",  score: 64, dScore: -3,  tier: 3, regime: "mix",  tech: "B",  vol: "C+", rr: 2.10, last: "07:43" },
    { asset: "COPX", side: "WATCH", score: 61, dScore: +1,  tier: 3, regime: "fit",  tech: "C+", vol: "B",  rr: 2.85, last: "07:40" },
    { asset: "NVDA", side: "WATCH", score: 58, dScore: -7,  tier: 3, regime: "mix",  tech: "B",  vol: "B+", rr: 1.90, last: "07:36" },
    { asset: "QQQ",  side: "AVOID", score: 49, dScore: -5,  tier: 4, regime: "off",  tech: "C",  vol: "C",  rr: 1.30, last: "07:31" },
    { asset: "HYG",  side: "AVOID", score: 44, dScore: -2,  tier: 4, regime: "off",  tech: "C-", vol: "C",  rr: 1.10, last: "07:29" },
    { asset: "ARKK", side: "AVOID", score: 38, dScore: -9,  tier: 4, regime: "off",  tech: "D",  vol: "C-", rr: 0.90, last: "07:25" },
  ],

  // ---------- Active trades ----------
  activeTrades: [
    {
      id: "t-2026-019", asset: "URA", side: "LONG",
      entry: 38.10, stop: 36.50, target: 47.50,
      sizeUsd: 32000, ageDays: 11,
      pnlPct: +6.42, pnlUsd: +2054,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 74, scoreNow: 88,
      status: "running",
    },
    {
      id: "t-2026-018", asset: "GLD", side: "LONG",
      entry: 261.20, stop: 257.00, target: 296.00,
      sizeUsd: 48000, ageDays: 18,
      pnlPct: +2.75, pnlUsd: +1320,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 79, scoreNow: 84,
      status: "running",
    },
    {
      id: "t-2026-017", asset: "XOP", side: "LONG",
      entry: 149.40, stop: 145.50, target: 168.00,
      sizeUsd: 28000, ageDays: 6,
      pnlPct: +1.81, pnlUsd: +507,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 70, scoreNow: 78,
      status: "running",
    },
    {
      id: "t-2026-016", asset: "ITA", side: "LONG",
      entry: 162.30, stop: 158.40, target: 178.00,
      sizeUsd: 22000, ageDays: 22,
      pnlPct: -0.62, pnlUsd: -136,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 67, scoreNow: 64,
      status: "near_invalidation",
    },
    {
      id: "t-2026-015", asset: "TLT", side: "SHORT",
      entry: 88.10, stop: 89.80, target: 81.50,
      sizeUsd: 30000, ageDays: 4,
      pnlPct: +1.93, pnlUsd: +578,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 76, scoreNow: 72,
      status: "running",
    },
    {
      id: "t-2026-014", asset: "COPX", side: "LONG",
      entry: 41.80, stop: 40.10, target: 48.00,
      sizeUsd: 24500, ageDays: 9,
      pnlPct: -1.20, pnlUsd: -294,
      regimeAtOpen: "Commodity-Led Inflation", scoreAtOpen: 68, scoreNow: 61,
      status: "watch",
    },
  ],

  // ---------- Reasoning trail (per-setup explain) ----------
  reasoning: {
    "sig-ura-2605": {
      total: 88,
      tier: 1,
      components: [
        { label: "Macro alignment",   score: 18, max: 20, color: "amber" },
        { label: "Liquidity",         score: 12, max: 15, color: "amber" },
        { label: "Sector strength",   score:  9, max: 10, color: "amber" },
        { label: "Technical structure", score: 13, max: 15, color: "green" },
        { label: "Volume confirm",    score:  9, max: 10, color: "green" },
        { label: "Risk / Reward",     score: 14, max: 15, color: "green" },
        { label: "Setup quality",     score:  8, max: 10, color: "amber" },
        { label: "Psychology · clean", score:  5, max:  5, color: "green" },
      ],
      modifiers: [
        { label: "Regime fit · commodity_led_inflation", value: "+8" },
        { label: "Failed-breakout penalty", value: "0" },
        { label: "Extended-from-support penalty", value: "0" },
      ],
      sources: [
        { name: "Doomberg",          weight: 0.92, freshness: "fresh", contrib: +14, tags: ["energy","commodities"] },
        { name: "Energy Capitalist", weight: 0.81, freshness: "fresh", contrib: +9,  tags: ["energy"] },
        { name: "FRED · CPI exp.",   weight: 0.78, freshness: "fresh", contrib: +6,  tags: ["macro"] },
        { name: "Capitalist Exploits", weight: 0.74, freshness: "1d", contrib: +4,  tags: ["thematic"] },
        { name: "Bianco Research",   weight: 0.68, freshness: "2d",   contrib: +3,  tags: ["macro"] },
        { name: "Twitter · @woodway", weight: 0.42, freshness: "fresh", contrib: +1,  tags: ["positioning"] },
      ],
      theses: [
        { theme: "Energy",      direction: "bullish", confidence: 0.81 },
        { theme: "Hard assets", direction: "bullish", confidence: 0.74 },
        { theme: "Tech / AI",   direction: "mixed",   confidence: 0.55 },
      ],
      agentBreakdown: [
        { agent: "regime_classifier",   model: "gemini-2.5-pro",     latencyMs: 820, costUsd: 0.018, ok: true },
        { agent: "narrative_synthesizer", model: "claude-haiku-4.5", latencyMs: 1240, costUsd: 0.012, ok: true },
        { agent: "score_composer",      model: "gemini-2.5-pro",     latencyMs: 690, costUsd: 0.011, ok: true },
        { agent: "chart_vision",        model: "gemini-2.5-pro",     latencyMs: 1980, costUsd: 0.024, ok: true },
        { agent: "rationale_writer",    model: "claude-haiku-4.5",   latencyMs: 540, costUsd: 0.005, ok: true },
      ],
    },
  },

  // ---------- Closed trades (journal) ----------
  closedTrades: [
    { id: "t-2026-013", asset: "GDX", side: "LONG", entry: 38.20, exit: 41.40, pnlPct: +8.38, holdDays: 14, scoreEntry: 81, regimeEntry: "Commodity-Led Inflation", thesis: "yes",     planClean: true,  lesson: "Held through 50DMA wobble — paid." },
    { id: "t-2026-012", asset: "URA", side: "LONG", entry: 35.70, exit: 33.40, pnlPct: -6.44, holdDays:  6, scoreEntry: 71, regimeEntry: "Transitional Chop",          thesis: "no",      planClean: true,  lesson: "Took setup in bad regime; framework warned." },
    { id: "t-2026-011", asset: "ITA", side: "LONG", entry: 158.10, exit: 168.00, pnlPct: +6.26, holdDays: 21, scoreEntry: 73, regimeEntry: "Commodity-Led Inflation",  thesis: "partial", planClean: true,  lesson: "Defense lagged then caught up; bigger size next." },
    { id: "t-2026-010", asset: "QQQ", side: "SHORT", entry: 521.40, exit: 528.10, pnlPct: -1.28, holdDays:  3, scoreEntry: 64, regimeEntry: "Dovish Liquidity Wave",   thesis: "no",      planClean: false, lesson: "Counter-regime short. Stop. Don't fade liquidity." },
    { id: "t-2026-009", asset: "GLD", side: "LONG", entry: 248.60, exit: 261.20, pnlPct: +5.07, holdDays:  9, scoreEntry: 78, regimeEntry: "Commodity-Led Inflation",  thesis: "yes",     planClean: true,  lesson: "Sized correctly; clean entry on 20DMA." },
    { id: "t-2026-008", asset: "COPX", side: "LONG", entry: 39.10, exit: 38.20, pnlPct: -2.30, holdDays:  4, scoreEntry: 66, regimeEntry: "Commodity-Led Inflation",  thesis: "partial", planClean: true,  lesson: "Right thesis, early entry — wait for retest hold." },
    { id: "t-2026-007", asset: "BTC", side: "LONG", entry: 67400, exit: 71200, pnlPct: +5.64, holdDays: 11, scoreEntry: 72, regimeEntry: "Dovish Liquidity Wave",     thesis: "yes",     planClean: true,  lesson: "Liquidity tape was clear; took it." },
    { id: "t-2026-006", asset: "TLT", side: "SHORT", entry: 91.20, exit: 88.10, pnlPct: +3.40, holdDays:  7, scoreEntry: 70, regimeEntry: "Commodity-Led Inflation",  thesis: "yes",     planClean: true,  lesson: "Term premium thesis paid quickly." },
    { id: "t-2026-005", asset: "ARKK", side: "SHORT", entry: 51.20, exit: 50.40, pnlPct: +1.56, holdDays:  2, scoreEntry: 62, regimeEntry: "Transitional Chop",      thesis: "partial", planClean: true,  lesson: "Took partial at first target; correct." },
    { id: "t-2026-004", asset: "DBA", side: "LONG", entry: 26.40, exit: 26.10, pnlPct: -1.14, holdDays: 12, scoreEntry: 65, regimeEntry: "Commodity-Led Inflation",  thesis: "no",      planClean: true,  lesson: "Ag fundamentals didn't catch — invalidation hit." },
  ],

  // Trades closed but not yet reviewed (review_status = closed_pending_review).
  // PM wires `desk_data.build_pending_reviews_section` after handback; this
  // mock keeps the journal SPA rendering during dev.
  pendingReviews: [
    {
      trade_id: "trd-2026-014",
      ticker: "XOP",
      side: "LONG",
      entry: 132.40,
      exit: 138.20,
      pnlPct: +4.38,
      pnl: 580,
      holdDays: 9,
      scoreEntry: 78,
      regimeEntry: "Commodity-Led Inflation",
      closedAt: "2026-05-09T15:14:00Z",
      candidateSources: ["Doomberg", "Energy Capitalist", "FRED · DGS10/CPI"],
    },
    {
      trade_id: "trd-2026-015",
      ticker: "PLTR",
      side: "LONG",
      entry: 24.60,
      exit: 22.10,
      pnlPct: -10.16,
      pnl: -1250,
      holdDays: 4,
      scoreEntry: 68,
      regimeEntry: "Transitional Chop",
      closedAt: "2026-05-09T18:42:00Z",
      candidateSources: ["@woodway (Twitter)", "Goldman GIR (S)"],
    },
    {
      trade_id: "trd-2026-016",
      ticker: "SLV",
      side: "LONG",
      entry: 28.10,
      exit: 28.85,
      pnlPct: +2.67,
      pnl: 375,
      holdDays: 5,
      scoreEntry: 74,
      regimeEntry: "Commodity-Led Inflation",
      closedAt: "2026-05-10T11:02:00Z",
      candidateSources: ["Doomberg", "Bianco Research"],
    },
  ],

  // Most recent submitted reviews — feeds lessons library. PM wires
  // `desk_data.build_lessons_library_section` from journal.recent_reviews.
  lessonsLibrary: [
    {
      trade_id: "t-2026-013", ticker: "GDX", completedAt: "2026-05-08T16:20:00Z",
      pnlPct: +8.38, thesisValidity: "fully_right",
      lesson: "Held through 50DMA wobble — paid. Regime tag was right.",
      executionScores: { entry: 5, stop: 5, sizing: 4, exit: 4 },
      surpriseFactor: [], wouldRetake: "yes",
      sourcesCredited: ["Doomberg", "Energy Capitalist"],
    },
    {
      trade_id: "t-2026-012", ticker: "URA", completedAt: "2026-05-04T14:00:00Z",
      pnlPct: -6.44, thesisValidity: "fully_wrong",
      lesson: "Took setup in bad regime; framework warned. Listen to chop tag.",
      executionScores: { entry: 3, stop: 4, sizing: 3, exit: 4 },
      surpriseFactor: ["sector"], wouldRetake: "no",
      sourcesCredited: ["@woodway (Twitter)"],
    },
    {
      trade_id: "t-2026-011", ticker: "ITA", completedAt: "2026-05-01T10:15:00Z",
      pnlPct: +6.26, thesisValidity: "right_thesis_wrong_outcome",
      lesson: "Defense lagged then caught up; size bigger when thesis early.",
      executionScores: { entry: 4, stop: 4, sizing: 2, exit: 5 },
      surpriseFactor: [], wouldRetake: "modified",
      sourcesCredited: ["Capitalist Exploits", "Bianco Research"],
    },
    {
      trade_id: "t-2026-010", ticker: "QQQ", completedAt: "2026-04-26T19:30:00Z",
      pnlPct: -1.28, thesisValidity: "fully_wrong",
      lesson: "Counter-regime short. Don't fade liquidity tape.",
      executionScores: { entry: 2, stop: 3, sizing: 3, exit: 4 },
      surpriseFactor: ["macro", "liquidity"], wouldRetake: "no",
      sourcesCredited: ["Bianco Research"],
    },
    {
      trade_id: "t-2026-009", ticker: "GLD", completedAt: "2026-04-22T13:45:00Z",
      pnlPct: +5.07, thesisValidity: "fully_right",
      lesson: "Sized correctly; clean 20DMA entry. Repeat this pattern.",
      executionScores: { entry: 5, stop: 5, sizing: 5, exit: 4 },
      surpriseFactor: [], wouldRetake: "yes",
      sourcesCredited: ["Doomberg", "FRED · DGS10/CPI"],
    },
    {
      trade_id: "t-2026-008", ticker: "COPX", completedAt: "2026-04-18T09:00:00Z",
      pnlPct: -2.30, thesisValidity: "right_thesis_wrong_outcome",
      lesson: "Right thesis, early entry — wait for the retest hold next time.",
      executionScores: { entry: 2, stop: 4, sizing: 3, exit: 4 },
      surpriseFactor: [], wouldRetake: "modified",
      sourcesCredited: ["Doomberg"],
    },
    {
      trade_id: "t-2026-007", ticker: "BTC", completedAt: "2026-04-14T20:10:00Z",
      pnlPct: +5.64, thesisValidity: "fully_right",
      lesson: "Liquidity tape was clear; took it without hesitation.",
      executionScores: { entry: 4, stop: 4, sizing: 4, exit: 5 },
      surpriseFactor: [], wouldRetake: "yes",
      sourcesCredited: ["Bianco Research", "@woodway (Twitter)"],
    },
    {
      trade_id: "t-2026-006", ticker: "TLT", completedAt: "2026-04-10T11:30:00Z",
      pnlPct: +3.40, thesisValidity: "right_outcome_wrong_reason",
      lesson: "Term premium thesis paid — but auction dynamics drove it, not CPI.",
      executionScores: { entry: 4, stop: 5, sizing: 4, exit: 4 },
      surpriseFactor: ["macro"], wouldRetake: "yes",
      sourcesCredited: ["FRED · DGS10/CPI", "Bianco Research"],
    },
  ],

  missedTrades: [
    { asset: "GDX", scoreAtTime: 82, reason: "missed_alert", validReal: true,  hindsightRisk: 2, lesson: "Set proper alerts on Tier-1 setups." },
    { asset: "ITA", scoreAtTime: 73, reason: "hesitation",   validReal: true,  hindsightRisk: 3, lesson: "Defense thesis was real-time clear; sized too small." },
    { asset: "OIH", scoreAtTime: 70, reason: "size_concern", validReal: true,  hindsightRisk: 4, lesson: "Correlation w/ XOP — should've routed XOP only." },
    { asset: "URNM", scoreAtTime: 76, reason: "duplicate",   validReal: false, hindsightRisk: 1, lesson: "URA already covered — no miss." },
  ],

  // J1 Process Scorecard — Trading Rule Framework v1 success metrics.
  // PM wires this from build_process_scorecard_section() in desk_data.py;
  // mock values illustrate what a 30-day disciplined book looks like.
  processScorecard: {
    days: 30,
    score: 82,
    metrics: [
      { label: "Rule adherence (30d mean)",       value: 84, of: 100 },
      { label: "High-confluence hit rate",        value: 71, of: 100 },
      { label: "Risk-per-trade compliance",       value: 92, of: 100 },
      { label: "Portfolio cap compliance",        value: 96, of: 100 },
      { label: "Setup-category diversification",  value: 73, of: 100 },
      { label: "Plan→outcome fidelity",           value: 78, of: 100 },
    ],
  },

  sourceLeaderboard: [
    { name: "Doomberg",            weight: 0.92, dWeight: +0.04, attribUsd: +6840, trades: 7, tags: ["energy","commodities"] },
    { name: "Energy Capitalist",   weight: 0.81, dWeight: +0.02, attribUsd: +3120, trades: 5, tags: ["energy"] },
    { name: "FRED · DGS10/CPI",    weight: 0.78, dWeight: 0.00,  attribUsd: +2470, trades: 9, tags: ["macro"] },
    { name: "Capitalist Exploits", weight: 0.74, dWeight: +0.01, attribUsd: +1810, trades: 4, tags: ["thematic"] },
    { name: "Bianco Research",     weight: 0.68, dWeight: -0.01, attribUsd: +890,  trades: 6, tags: ["macro","rates"] },
    { name: "Goldman GIR (S)",     weight: 0.62, dWeight: -0.02, attribUsd: +420,  trades: 3, tags: ["sell-side"] },
    { name: "@woodway (Twitter)",  weight: 0.42, dWeight: -0.06, attribUsd: -380,  trades: 4, tags: ["positioning"] },
    { name: "ZeroHedge RSS",       weight: 0.28, dWeight: -0.08, attribUsd: -640,  trades: 3, tags: ["news"] },
  ],

  // Spearman ρ between score components and realized PnL %.
  // Empty until closed trades exist; SPA renders zero-state from the same shape.
  scoreCorrelation: {
    n_pairs: 14,
    components: [
      { name: "adjusted_total",       spearman: +0.42, p_value: 0.13, n: 14 },
      { name: "macro_alignment",      spearman: +0.31, p_value: 0.27, n: 14 },
      { name: "liquidity",            spearman: +0.18, p_value: 0.54, n: 14 },
      { name: "sector_theme",         spearman: +0.55, p_value: 0.04, n: 14 },
      { name: "technical_structure",  spearman: +0.38, p_value: 0.18, n: 14 },
      { name: "volume_flow",          spearman: +0.22, p_value: 0.45, n: 14 },
      { name: "risk_reward",          spearman: +0.49, p_value: 0.07, n: 14 },
      { name: "relative_strength",    spearman: +0.27, p_value: 0.34, n: 14 },
      { name: "psychology",           spearman: -0.08, p_value: 0.78, n: 14 },
    ],
  },

  thesisChangelog: [
    { date: "2026-04-22", from: "v2.4", to: "v3.0", title: "Capital Rotation Through Hyper-Liquidity Cycle", summary: "Reframed as two-speed market. Energy + AI explicitly linked. Cash treated as strategic, not residual.", regimes: ["+commodity_expansion", "+monetary_debasement_hard_asset"] },
    { date: "2026-03-08", from: "v2.3", to: "v2.4", title: "Defense as early signal", summary: "Defense recognized as leading rather than late-cycle on procurement tape.", regimes: [] },
    { date: "2026-01-30", from: "v2.2", to: "v2.3", title: "Liquidity-led mechanics formalized", summary: "Distinguished short-term liquidity layer from medium-term structural layer.", regimes: ["+dovish_liquidity_wave"] },
  ],

  // ---------- /dev surfaces ----------
  brainActivity: [
    { ts: "08:14:22", agent: "score_composer",       model: "gemini-2.5-pro",   latencyMs: 690,  tokensIn: 2840, tokensOut: 412, costUsd: 0.011, ok: true },
    { ts: "08:14:11", agent: "narrative_synthesizer", model: "claude-haiku-4.5", latencyMs: 1240, tokensIn: 6210, tokensOut: 924, costUsd: 0.012, ok: true },
    { ts: "08:13:58", agent: "regime_classifier",    model: "gemini-2.5-pro",   latencyMs: 820,  tokensIn: 4180, tokensOut: 188, costUsd: 0.018, ok: true },
    { ts: "08:13:42", agent: "chart_vision",         model: "gemini-2.5-pro",   latencyMs: 1980, tokensIn: 1890, tokensOut: 311, costUsd: 0.024, ok: true },
    { ts: "08:13:14", agent: "rationale_writer",     model: "claude-haiku-4.5", latencyMs: 540,  tokensIn: 1820, tokensOut: 396, costUsd: 0.005, ok: true },
    { ts: "08:12:52", agent: "transcription",        model: "gemini-2.5-flash", latencyMs: 4120, tokensIn:    0, tokensOut:   0, costUsd: 0.041, ok: true },
    { ts: "08:11:46", agent: "score_composer",       model: "gemini-2.5-pro",   latencyMs: 720,  tokensIn: 2790, tokensOut: 401, costUsd: 0.011, ok: true },
    { ts: "08:09:32", agent: "score_composer",       model: "gemini-2.5-pro",   latencyMs: 740,  tokensIn: 2810, tokensOut: 408, costUsd: 0.011, ok: true },
    { ts: "08:08:11", agent: "vision",               model: "gemini-2.5-pro",   latencyMs: 2400, tokensIn: 1740, tokensOut: 240, costUsd: 0.022, ok: false },
    { ts: "08:07:09", agent: "narrative_synthesizer", model: "claude-haiku-4.5", latencyMs: 1180, tokensIn: 5980, tokensOut: 880, costUsd: 0.011, ok: true },
  ],

  sourceHealth: [
    { name: "Doomberg",            source_id: "doomberg",            kind: "Substack",      lastFetch: "08:02", freshness: 1.00, weight: 0.92, attrib30d: +6840, tags: ["energy"],
      author: "Doomberg",          market_focus: "energy, commodities", research_style: "contrarian",   fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["substack","rss"], onboarded_at: "2025-11-01" },
    { name: "Capitalist Exploits", source_id: "capitalist_exploits", kind: "Substack",      lastFetch: "07:56", freshness: 0.96, weight: 0.74, attrib30d: +1810, tags: ["thematic"],
      author: "Chris MacIntosh",   market_focus: "thematic, hard assets", research_style: "thematic",  fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["substack"],      onboarded_at: "2026-01-15" },
    { name: "Bianco Research",     source_id: "bianco_research",     kind: "Substack",      lastFetch: "06:14", freshness: 0.71, weight: 0.68, attrib30d: +890,  tags: ["macro"],
      author: "Jim Bianco",        market_focus: "rates, macro",        research_style: "data-driven", fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["substack"],      onboarded_at: "2026-01-10" },
    { name: "Energy Capitalist",   source_id: "energy_capitalist",   kind: "Newsletter",    lastFetch: "08:11", freshness: 1.00, weight: 0.81, attrib30d: +3120, tags: ["energy"],
      author: "Josh Young",        market_focus: "energy, E&P",         research_style: "fundamental", fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["email","rss"],   onboarded_at: "2025-12-01" },
    { name: "FRED · DGS10",        source_id: "fred",                kind: "Data feed",     lastFetch: "08:14", freshness: 1.00, weight: 0.78, attrib30d: +2470, tags: ["macro"],
      author: "Federal Reserve",   market_focus: "rates, macro",        research_style: "data",        fetch_cadence: "daily",        freshness_sla_hours: 24,  channels: ["api"],           onboarded_at: "2025-10-01" },
    { name: "FRED · CPI exp.",     source_id: "fred",                kind: "Data feed",     lastFetch: "08:14", freshness: 1.00, weight: 0.78, attrib30d: +2470, tags: ["macro"],
      author: "Federal Reserve",   market_focus: "inflation, macro",    research_style: "data",        fetch_cadence: "daily",        freshness_sla_hours: 24,  channels: ["api"],           onboarded_at: "2025-10-01" },
    { name: "Forward Guidance",    source_id: "forward_guidance",    kind: "Podcast (RSS)", lastFetch: "Yest",  freshness: 0.42, weight: 0.61, attrib30d: +210,  tags: ["macro","podcast"],
      author: "Jack Farley",       market_focus: "macro, rates, credit",research_style: "interview",   fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["rss","podcast"], onboarded_at: "2026-01-20" },
    { name: "Macro Voices",        source_id: "macro_voices",        kind: "Podcast (RSS)", lastFetch: "2d",    freshness: 0.18, weight: 0.55, attrib30d: -120,  tags: ["macro","podcast"],
      author: "Erik Townsend",     market_focus: "macro, energy",       research_style: "interview",   fetch_cadence: "weekly",       freshness_sla_hours: 168, channels: ["rss","podcast"], onboarded_at: "2026-01-25" },
    { name: "ZeroHedge",           source_id: "zerohedge_rss",       kind: "RSS",           lastFetch: "08:10", freshness: 0.99, weight: 0.28, attrib30d: -640,  tags: ["news"],
      author: "ZeroHedge",         market_focus: "news, geopolitics",   research_style: "aggregator",  fetch_cadence: "hourly",       freshness_sla_hours: 4,   channels: ["rss"],           onboarded_at: "2025-10-15" },
    { name: "@woodway",            source_id: "woodway_twitter",     kind: "Twitter",       lastFetch: "08:13", freshness: 1.00, weight: 0.42, attrib30d: -380,  tags: ["positioning"],
      author: "@woodway",          market_focus: "positioning, tech",   research_style: "social",      fetch_cadence: "daily",        freshness_sla_hours: 12,  channels: ["twitter"],       onboarded_at: "2026-02-10" },
  ],

  costTracker: {
    today: 4.82, week: 28.16, month: 112.40,
    capDaily: 25, capMonthly: 600,
    byAgent: [
      { agent: "narrative_synthesizer", usd: 1.84 },
      { agent: "regime_classifier",     usd: 1.12 },
      { agent: "score_composer",        usd: 0.78 },
      { agent: "chart_vision",          usd: 0.61 },
      { agent: "transcription",         usd: 0.32 },
      { agent: "rationale_writer",      usd: 0.15 },
    ],
    byBackend: [
      { backend: "Gemini 2.5 Pro",     usd: 3.21 },
      { backend: "Claude Haiku 4.5",   usd: 1.29 },
      { backend: "Gemini 2.5 Flash",   usd: 0.32 },
    ],
    spike: false,
  },

  mgmt: {
    todos: [
      { status: "in_flight",    title: "Wire /journal endpoints in macro-analyzer API",         owner: "Application Agent", age: "2h" },
      { status: "in_flight",    title: "Add chart_vision retry on rate-limit",                  owner: "Application Agent", age: "5h" },
      { status: "blocked",      title: "Re-tune setup score weights against last 30 closed",   owner: "Framework Agent",   age: "1d" },
      { status: "todo",         title: "Add Glassnode connector for stablecoin liquidity",      owner: "Application Agent", age: "—" },
      { status: "todo",         title: "Quarterly thesis review · v3.1 candidate",              owner: "Thesis Agent",      age: "—" },
      { status: "done",         title: "Migrate to Gemini 2.5 Pro for regime_classifier",       owner: "Application Agent", age: "12h" },
    ],
    decisions: [
      { date: "2026-05-08", title: "Manual-execution-first stays through Phase 8", who: "Operator" },
      { date: "2026-05-06", title: "Score Δ visualized over absolute score on hero cards", who: "Operator + Application Agent" },
      { date: "2026-05-02", title: "Doomberg weight raised to 0.92 after attribution review", who: "Framework Agent" },
    ],
    commits: [
      { hash: "5533b3a", author: "thommi", msg: "dashboard: refine positioning shell (gradient strip, hero signals)" },
      { hash: "a14e09c", author: "thommi", msg: "brain: gemini 2.5 pro for regime_classifier" },
      { hash: "7e2b1d4", author: "thommi", msg: "ingestion: per-source freshness weighting" },
      { hash: "9c01a8f", author: "thommi", msg: "framework: tighten failed-breakout penalty (-15→-18)" },
      { hash: "31b770a", author: "thommi", msg: "db: add missed_trades table" },
    ],
  },

  integration: {
    tactical: { connected: true, lastPoll: "08:14:30", contractVersion: "v3", schemaDrift: false, mode: "manual" },
  },

  // ---------- Funnel spine (concepts / plans) ----------
  // Step ② Concepts — marked watchlist items that survive between
  // sessions. Each row carries its score snapshot and any thesis note
  // the operator wrote when marking. Promotion to step ③ creates a
  // trade_plan and links it back here for lineage.
  conceptSuggestions: [
    { asset: "DBA", score: 65, dScore: +2, tier: 3, side: "WATCH", regime: "fit",
      reason: "score 65 · grade B · ag tape firming · regime fit" },
    { asset: "ITA", score: 64, dScore: -3, tier: 3, side: "LONG", regime: "mix",
      reason: "score 64 · defense procurement re-accelerating" },
    { asset: "COPX", score: 61, dScore: +1, tier: 3, side: "WATCH", regime: "fit",
      reason: "score 61 · copper supply tightness · regime fit" },
  ],

  concepts: [
    {
      id: "concept-001",
      asset: "URA",
      source: "watchlist_manual",
      status: "active",
      suggestedBySystem: false,
      suggestionReason: null,
      scoreAtMark: 88,
      tierAtMark: 1,
      sideAtMark: "LONG",
      thesis: "Reactor restart cadence + physical U3O8 firming. Wait for retest of 41.20 before sizing.",
      markedAt: "2026-05-08 09:14",
      tradePlanId: null,
    },
    {
      id: "concept-002",
      asset: "GLD",
      source: "watchlist_manual",
      status: "active",
      suggestedBySystem: false,
      suggestionReason: null,
      scoreAtMark: 84,
      tierAtMark: 1,
      sideAtMark: "LONG",
      thesis: "Real yields rolled over. Central-bank tape +47t May. Want 50DMA hold confirmation.",
      markedAt: "2026-05-09 11:42",
      tradePlanId: null,
    },
    {
      id: "concept-003",
      asset: "XOP",
      source: "watchlist_auto",
      status: "promoted",
      suggestedBySystem: true,
      suggestionReason: "score 78 · grade B+ · breakout continuation",
      scoreAtMark: 78,
      tierAtMark: 2,
      sideAtMark: "LONG",
      thesis: "Brent above 86, breadth at 28d high. Take on continuation.",
      markedAt: "2026-05-05 08:30",
      promotedAt: "2026-05-06 10:12",
      tradePlanId: "plan-001",
    },
  ],

  // Step ③ Plans — draft + live + closed trade plans. Each plan
  // optionally links to the concept it grew from (concept_id) and
  // to the trades row it activated into (tradeId).
  plans: [
    {
      id: "plan-001",
      conceptId: "concept-003",
      asset: "XOP",
      side: "LONG",
      entry: 149.40,
      stop: 145.50,
      targets: [{ price: 158.00, weight: 0.5 }, { price: 168.00, weight: 0.5 }],
      sizeUsd: 28000,
      sizeR: 1.0,
      timeHorizon: "swing",
      thesis: "Energy breakout continuation; sector breadth strong.",
      invalidation: "Close below 145.50 on volume, or Brent loses 84.",
      gateStatus: "pass",
      status: "live",
      tradeId: "t-2026-017",
      createdAt: "2026-05-06 10:12",
      activatedAt: "2026-05-06 14:01",
    },
    {
      id: "plan-002",
      conceptId: null,
      asset: "URA",
      side: "LONG",
      entry: 41.20,
      stop: 39.40,
      targets: [{ price: 44.50, weight: 0.4 }, { price: 47.50, weight: 0.6 }],
      sizeUsd: null,
      sizeR: 1.0,
      timeHorizon: "swing",
      thesis: "Long base accumulation breakout retest.",
      invalidation: "Daily close below 39.40 or U3O8 spot breaks $90.",
      gateStatus: "warn",
      status: "draft",
      tradeId: null,
      createdAt: "2026-05-10 08:22",
      activatedAt: null,
    },
  ],

  // ---------- Streams (who's saying what across the 26 sources) ----------
  // High-level digest per source so the operator can sanity-check the
  // tape without going into each substack/RSS feed individually. The
  // brain summarises the last N items per source on each ingest pass
  // and writes one row here; the SPA renders by theme + recency. The
  // `topVoices` rollup groups recurring narrative arcs across sources.
  streams: {
    asOf: "2026-05-10 08:14",

    // S1 — Animated theme scatter map data
    themeMap: [
      {
        id: "uranium_energy",
        label: "Uranium / Energy",
        direction: "bullish",
        lifecycle: 0.28,
        novelty: 0.84,
        velocity: 0.74,
        age_days: 28,
        mentions_by_week: [4, 7, 11, 14],
        sources: ["doomberg", "energy_capitalist", "capitalist_exploits"],
      },
      {
        id: "power_grid_stress",
        label: "Power-Grid Stress",
        direction: "bullish",
        lifecycle: 0.12,
        novelty: 0.91,
        velocity: 0.88,
        age_days: 6,
        mentions_by_week: [0, 2, 6, 11],
        sources: ["doomberg", "bianco_research"],
      },
      {
        id: "gold_debasement",
        label: "Gold / Debasement",
        direction: "bullish",
        lifecycle: 0.52,
        novelty: 0.71,
        velocity: 0.61,
        age_days: 42,
        mentions_by_week: [6, 8, 9, 9],
        sources: ["doomberg", "fred", "bianco_research"],
      },
      {
        id: "rates_term_premium",
        label: "Rates / Term Premium",
        direction: "bearish",
        lifecycle: 0.61,
        novelty: 0.62,
        velocity: 0.55,
        age_days: 35,
        mentions_by_week: [3, 5, 6, 7],
        sources: ["bianco_research", "fred", "goldman_gir"],
      },
      {
        id: "ai_capex",
        label: "AI Capex Narrative",
        direction: "mixed",
        lifecycle: 0.44,
        novelty: 0.58,
        velocity: 0.41,
        age_days: 21,
        mentions_by_week: [5, 9, 11, 8],
        sources: ["woodway_twitter", "zerohedge_rss"],
      },
      {
        id: "copper_supply",
        label: "Copper Supply Crunch",
        direction: "bullish",
        lifecycle: 0.19,
        novelty: 0.77,
        velocity: 0.63,
        age_days: 10,
        mentions_by_week: [0, 1, 3, 7],
        sources: ["energy_capitalist", "capitalist_exploits"],
      },
    ],

    // S2 — Emerging concepts cards (novelty > 0.7, velocity > 0.4)
    concepts: [
      {
        id: "power_grid_bottleneck",
        title: "Power-grid bottleneck",
        synopsis: "ERCOT capacity headlines + transformer lead-time stretching to 220wks. Crosses uranium + AI-capex.",
        novelty: 0.91,
        velocity: 0.88,
        items_count: 7,
        sources_count: 2,
        source_names: ["Doomberg", "Bianco Research"],
        age_days: 6,
      },
      {
        id: "uranium_physical_reclaim",
        title: "U₃O₈ physical reclaim",
        synopsis: "$94 spot price reclaim accelerating; Cameco hand-to-mouth contracts becoming an issue. Utility buying window narrowing.",
        novelty: 0.84,
        velocity: 0.74,
        items_count: 14,
        sources_count: 3,
        source_names: ["Doomberg", "Energy Capitalist", "Capitalist Exploits"],
        age_days: 28,
      },
      {
        id: "copper_supply_gap",
        title: "Copper supply gap",
        synopsis: "Mine-to-market timeline stretching; no new greenfield permitted. Crosses AI data-center + grid-stress thesis.",
        novelty: 0.77,
        velocity: 0.63,
        items_count: 4,
        sources_count: 2,
        source_names: ["Energy Capitalist", "Capitalist Exploits"],
        age_days: 10,
      },
      {
        id: "gold_cb_buying",
        title: "Central-bank gold accumulation",
        synopsis: "+47t May CB buying; real-yield rollover reactivating the debasement thesis. Positioning below Q4'25 peak.",
        novelty: 0.71,
        velocity: 0.61,
        items_count: 9,
        sources_count: 3,
        source_names: ["Doomberg", "FRED", "Bianco Research"],
        age_days: 42,
      },
    ],

    // S3 — Source network graph (nodes + echo-tie links)
    sourceGraph: {
      nodes: [
        // — T0 · TRUSTED KOL (manual capture; highest-conviction parent voices) —
        // The existing Stock Unlocked entry further down is promoted to T0 too.
        { id: "feather_hands",     name: "Feather Hands",     tier: 0, weight: 0.97, market_focus: "equities, factors",
          source_id: "feather_hands", kind: "Manual (KOL)", attrib30d: 9420, freshness: "fresh",
          author: "Feather Hands", research_style: "discretionary", fetch_cadence: "as-dropped",
          freshness_sla_hours: 24, channels: ["manual","chat"], onboarded_at: "2025-09-15",
          tags: ["kol","trusted","parent_voice"] },

        { id: "doomberg",           name: "Doomberg",          tier: 1, weight: 0.92, market_focus: "energy",
          source_id: "doomberg", kind: "Substack", attrib30d: 6840, freshness: "fresh",
          author: "Doomberg", research_style: "contrarian", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack","rss"], onboarded_at: "2025-11-01",
          tags: ["energy","commodities"] },
        { id: "energy_capitalist",  name: "Energy Capitalist", tier: 1, weight: 0.81, market_focus: "energy",
          source_id: "energy_capitalist", kind: "Newsletter", attrib30d: 3120, freshness: "fresh",
          author: "Josh Young", research_style: "fundamental", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["email","rss"], onboarded_at: "2025-12-01",
          tags: ["energy"] },
        { id: "fred",               name: "FRED",              tier: 1, weight: 0.78, market_focus: "macro",
          source_id: "fred", kind: "Data feed", attrib30d: 2470, freshness: "fresh",
          author: "Federal Reserve", research_style: "data", fetch_cadence: "daily",
          freshness_sla_hours: 24, channels: ["api"], onboarded_at: "2025-10-01",
          tags: ["macro","rates"] },
        { id: "bianco_research",    name: "Bianco Research",   tier: 2, weight: 0.68, market_focus: "macro",
          source_id: "bianco_research", kind: "Substack", attrib30d: 890, freshness: "fresh",
          author: "Jim Bianco", research_style: "data-driven", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack"], onboarded_at: "2026-01-10",
          tags: ["macro","rates"] },
        { id: "capitalist_exploits", name: "Capitalist Exploits", tier: 2, weight: 0.74, market_focus: "energy",
          source_id: "capitalist_exploits", kind: "Substack", attrib30d: 1810, freshness: "fresh",
          author: "Chris MacIntosh", research_style: "thematic", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack"], onboarded_at: "2026-01-15",
          tags: ["thematic","commodities"] },
        { id: "goldman_gir",        name: "Goldman GIR",       tier: 2, weight: 0.62, market_focus: "macro",
          source_id: "goldman_gir", kind: "Sell-side", attrib30d: 420, freshness: "1d",
          author: "Goldman Sachs GIR", research_style: "sell-side", fetch_cadence: "as-published",
          freshness_sla_hours: 72, channels: ["manual"], onboarded_at: "2026-02-01",
          tags: ["sell-side"] },
        { id: "forward_guidance",   name: "Forward Guidance",  tier: 1, weight: 0.85, market_focus: "macro",
          source_id: "forward_guidance", kind: "Podcast (RSS)", attrib30d: 210, freshness: "1d",
          author: "Jack Farley", research_style: "interview", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["rss","podcast"], onboarded_at: "2026-01-20",
          tags: ["macro","podcast"] },

        // — MANUAL · TRUSTED — Feather Hands family + Stock Unlocked.
        // User's top sources for direct trades AND macro sentiment.
        // Mapped to clusters by their dominant analysis bucket.
        { id: "big_nuts",           name: "Big_Nuts",          tier: 0, weight: 0.93, market_focus: "crypto",
          source_id: "big_nuts", kind: "Manual · Telegram", attrib30d: 0, freshness: "fresh",
          author: "Big_Nuts", research_style: "TA / multi-asset", fetch_cadence: "manual",
          freshness_sla_hours: 24, channels: ["telegram","manual_input"], onboarded_at: "2026-05-11",
          tags: ["direct_trades","crypto","gold","commodities","equities","manual","trusted"],
          parent_channel: "Feather Hands", group: "Market Traders" },
        { id: "joejoe55",           name: "joejoe55",          tier: 0, weight: 0.90, market_focus: "crypto",
          source_id: "joejoe55", kind: "Manual · Telegram", attrib30d: 0, freshness: "fresh",
          author: "joejoe55", research_style: "TA / setups", fetch_cadence: "manual",
          freshness_sla_hours: 24, channels: ["telegram","manual_input"], onboarded_at: "2026-05-31",
          tags: ["direct_trades","both","manual","trusted"],
          parent_channel: "Feather Hands", group: "Feather Hands direct" },
        { id: "maddog31",           name: "MadDog31",          tier: 2, weight: 0.72, market_focus: "crypto",
          source_id: "maddog31", kind: "Manual · Telegram", attrib30d: 0, freshness: "fresh",
          author: "MadDog31", research_style: "TA", fetch_cadence: "manual",
          freshness_sla_hours: 24, channels: ["telegram","manual_input"], onboarded_at: "2026-05-11",
          tags: ["direct_trades","manual"],
          parent_channel: "Feather Hands", group: "Market Traders" },
        { id: "stock_unlocked",     name: "Stock Unlocked",    tier: 0, weight: 0.94, market_focus: "equities",
          source_id: "stock_unlocked", kind: "Manual · Telegram", attrib30d: 0, freshness: "fresh",
          author: "Stock Unlocked", research_style: "stock-picking", fetch_cadence: "manual",
          freshness_sla_hours: 24, channels: ["telegram","manual_input"], onboarded_at: "2026-05-11",
          tags: ["direct_trades","equities","manual","parent_voice"],
          parent_channel: null, group: "Stock Unlocked" },
        { id: "artur_unlocked",     name: "Artur Unlocked",    tier: 0, weight: 0.91, market_focus: "equities",
          source_id: "artur_unlocked", kind: "Manual · Telegram", attrib30d: 0, freshness: "fresh",
          author: "Artur Unlocked", research_style: "swing TA", fetch_cadence: "manual",
          freshness_sla_hours: 24, channels: ["telegram","manual_input"], onboarded_at: "2026-05-11",
          tags: ["direct_trades","equities","manual","parent_voice","trusted"],
          parent_channel: "Stock Unlocked", group: "Stock Unlocked" },
        { id: "woodway_twitter",    name: "@woodway",          tier: 4, weight: 0.42, market_focus: "social",
          source_id: "woodway_twitter", kind: "Twitter", attrib30d: -380, freshness: "fresh",
          author: "@woodway", research_style: "social", fetch_cadence: "daily",
          freshness_sla_hours: 12, channels: ["twitter"], onboarded_at: "2026-02-10",
          tags: ["positioning","tech"] },
        { id: "zerohedge_rss",      name: "ZeroHedge",         tier: 4, weight: 0.28, market_focus: "social",
          source_id: "zerohedge_rss", kind: "RSS", attrib30d: -640, freshness: "fresh",
          author: "ZeroHedge", research_style: "aggregator", fetch_cadence: "hourly",
          freshness_sla_hours: 4, channels: ["rss"], onboarded_at: "2025-10-15",
          tags: ["news"] },

        // — EQUITIES · FACTORS —
        { id: "goldman_equities", name: "Goldman Equities", tier: 2, weight: 0.66, market_focus: "equities",
          source_id: "goldman_equities", kind: "Sell-side", attrib30d: 1120, freshness: "fresh",
          author: "Goldman Sachs Equity Strategy", research_style: "sell-side", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["manual"], onboarded_at: "2026-01-22",
          tags: ["equities","sectors"] },
        { id: "kalecki_note",   name: "Kalecki Note",     tier: 2, weight: 0.71, market_focus: "equities, factors",
          source_id: "kalecki_note", kind: "Substack", attrib30d: 840, freshness: "fresh",
          author: "Aaron Brown", research_style: "factor", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack"], onboarded_at: "2026-01-18",
          tags: ["factors","equities"] },

        // — TECH · AI —
        { id: "stratechery",    name: "Stratechery",      tier: 2, weight: 0.69, market_focus: "tech",
          source_id: "stratechery", kind: "Substack", attrib30d: 720, freshness: "fresh",
          author: "Ben Thompson", research_style: "thematic", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack","podcast"], onboarded_at: "2026-01-12",
          tags: ["tech","ai"] },
        { id: "semianalysis",   name: "SemiAnalysis",     tier: 1, weight: 0.83, market_focus: "tech, semiconductor, ai",
          source_id: "semianalysis", kind: "Substack", attrib30d: 1980, freshness: "fresh",
          author: "Dylan Patel", research_style: "supply-chain", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["substack"], onboarded_at: "2025-12-20",
          tags: ["semis","ai"] },

        // — CRYPTO · DIGITAL —
        { id: "glassnode",      name: "Glassnode",        tier: 1, weight: 0.79, market_focus: "crypto, on-chain",
          source_id: "glassnode", kind: "Data feed", attrib30d: 1340, freshness: "fresh",
          author: "Glassnode", research_style: "data", fetch_cadence: "daily",
          freshness_sla_hours: 24, channels: ["api"], onboarded_at: "2025-12-05",
          tags: ["crypto","onchain"] },
        { id: "messari",        name: "Messari",          tier: 3, weight: 0.52, market_focus: "crypto, digital",
          source_id: "messari", kind: "Newsletter", attrib30d: 240, freshness: "1d",
          author: "Messari Research", research_style: "research", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["email"], onboarded_at: "2026-02-05",
          tags: ["crypto"] },

        // — REAL ASSETS · GOLD —
        { id: "incrementum",    name: "Incrementum",      tier: 2, weight: 0.72, market_focus: "real_assets, gold",
          source_id: "incrementum", kind: "Research", attrib30d: 1050, freshness: "1d",
          author: "Ronald-Peter Stöferle", research_style: "thematic", fetch_cadence: "quarterly",
          freshness_sla_hours: 720, channels: ["pdf"], onboarded_at: "2025-11-10",
          tags: ["gold","real_assets"] },

        // — CREDIT · FIXED INCOME —
        { id: "credit_bubble",  name: "Credit Bubble Bulletin", tier: 2, weight: 0.58, market_focus: "credit, fixed_income",
          source_id: "credit_bubble", kind: "Newsletter", attrib30d: 320, freshness: "1d",
          author: "Doug Noland", research_style: "credit", fetch_cadence: "weekly",
          freshness_sla_hours: 168, channels: ["email"], onboarded_at: "2026-01-28",
          tags: ["credit","spreads"] },
        { id: "marc_to_market", name: "Marc Chandler",    tier: 3, weight: 0.55, market_focus: "credit, fi",
          source_id: "marc_to_market", kind: "Blog", attrib30d: 140, freshness: "fresh",
          author: "Marc Chandler", research_style: "fundamental", fetch_cadence: "daily",
          freshness_sla_hours: 24, channels: ["rss"], onboarded_at: "2026-02-12",
          tags: ["fi","fx"] },

        // — FX · GEOPOLITICS —
        { id: "brent_donnelly", name: "Brent Donnelly",   tier: 1, weight: 0.86, market_focus: "fx",
          source_id: "brent_donnelly", kind: "Substack", attrib30d: 2240, freshness: "fresh",
          author: "Brent Donnelly", research_style: "fx-trader", fetch_cadence: "daily",
          freshness_sla_hours: 24, channels: ["substack"], onboarded_at: "2025-11-20",
          tags: ["fx","positioning"] },
        { id: "zoltan_notes",   name: "Zoltan Notes",     tier: 2, weight: 0.74, market_focus: "fx, geopolitics, currency",
          source_id: "zoltan_notes", kind: "Research", attrib30d: 690, freshness: "1d",
          author: "Zoltan Pozsar", research_style: "structural", fetch_cadence: "as-published",
          freshness_sla_hours: 168, channels: ["pdf"], onboarded_at: "2025-12-15",
          tags: ["fx","geopolitics"] },
      ],
      links: [
        // Energy cluster
        { source: "doomberg",          target: "energy_capitalist",   strength: 0.82 },
        { source: "doomberg",          target: "capitalist_exploits", strength: 0.71 },
        { source: "energy_capitalist", target: "capitalist_exploits", strength: 0.67 },
        // Macro cluster
        { source: "doomberg",          target: "bianco_research",     strength: 0.54 },
        { source: "fred",              target: "bianco_research",     strength: 0.61 },
        { source: "fred",              target: "goldman_gir",         strength: 0.48 },
        { source: "bianco_research",   target: "goldman_gir",         strength: 0.44 },
        // News/social
        { source: "woodway_twitter",   target: "zerohedge_rss",       strength: 0.38 },
        { source: "forward_guidance",  target: "bianco_research",     strength: 0.35 },
        // Equities ↔ Macro
        { source: "goldman_equities",  target: "goldman_gir",         strength: 0.58 },
        { source: "kalecki_note",      target: "bianco_research",     strength: 0.42 },
        { source: "kalecki_note",      target: "goldman_equities",    strength: 0.36 },
        // Tech ↔ Equities
        { source: "semianalysis",      target: "stratechery",         strength: 0.61 },
        { source: "semianalysis",      target: "goldman_equities",    strength: 0.39 },
        { source: "stratechery",       target: "woodway_twitter",     strength: 0.28 },
        // Crypto
        { source: "glassnode",         target: "messari",             strength: 0.55 },
        { source: "glassnode",         target: "doomberg",            strength: 0.31 },
        // Real assets ↔ Macro/Energy
        { source: "incrementum",       target: "doomberg",            strength: 0.46 },
        { source: "incrementum",       target: "fred",                strength: 0.38 },
        { source: "incrementum",       target: "bianco_research",     strength: 0.34 },
        // Credit
        { source: "credit_bubble",     target: "fred",                strength: 0.44 },
        { source: "credit_bubble",     target: "bianco_research",     strength: 0.41 },
        { source: "marc_to_market",    target: "credit_bubble",       strength: 0.32 },
        // FX
        { source: "brent_donnelly",    target: "marc_to_market",      strength: 0.48 },
        { source: "zoltan_notes",      target: "brent_donnelly",      strength: 0.52 },
        { source: "zoltan_notes",      target: "bianco_research",     strength: 0.39 },
        // Manual · Feather Hands family — intra-cluster ties + outward
        // ties to the macro / metals / energy sources they cite.
        { source: "big_nuts",          target: "joejoe55",            strength: 0.78 },
        { source: "big_nuts",          target: "maddog31",            strength: 0.72 },
        { source: "joejoe55",          target: "maddog31",            strength: 0.61 },
        { source: "big_nuts",          target: "doomberg",            strength: 0.52 },
        { source: "big_nuts",          target: "incrementum",         strength: 0.58 },
        { source: "joejoe55",          target: "forward_guidance",    strength: 0.48 },
        { source: "stock_unlocked",    target: "artur_unlocked",      strength: 0.82 },
        { source: "stock_unlocked",    target: "kalecki_note",        strength: 0.44 },
        { source: "artur_unlocked",    target: "goldman_equities",    strength: 0.41 },
        { source: "big_nuts",          target: "stock_unlocked",      strength: 0.39 },
        // T0 parent voices anchor their sub-cluster + cite high-weight sources.
        { source: "feather_hands",     target: "big_nuts",            strength: 0.84 },
        { source: "feather_hands",     target: "joejoe55",            strength: 0.78 },
        { source: "feather_hands",     target: "maddog31",            strength: 0.66 },
        { source: "feather_hands",     target: "stock_unlocked",      strength: 0.58 },
        { source: "feather_hands",     target: "doomberg",            strength: 0.41 },
        { source: "stock_unlocked",    target: "kalecki_note",        strength: 0.46 },
        { source: "stock_unlocked",    target: "semianalysis",        strength: 0.43 },
      ],
    },

    summary:
      "Energy + hard assets continue to dominate the narrative across high-weight sources. Doomberg + Energy Capitalist are leaning into uranium + power-grid stress; Bianco is the lone dissenter on rates (calling term-premium reversal). News-tier RSS is contributing noise — flagged as low-weight by attribution.",
    topVoices: [
      {
        theme: "Energy / uranium",
        direction: "bullish",
        sources: ["Doomberg", "Energy Capitalist", "Capitalist Exploits"],
        items: 14, lastUpdate: "08:14",
        synopsis: "Reactor restart cadence + grid-stress thesis is the highest-conviction cluster. Physical U3O8 reclaim of $94 cited 6× this week.",
      },
      {
        theme: "Real assets / debasement",
        direction: "bullish",
        sources: ["Doomberg", "FRED · DGS10/CPI", "Bianco Research"],
        items: 9, lastUpdate: "08:11",
        synopsis: "Real-yield rollover + central-bank gold buying (+47t May) re-energising the gold thesis. Positioning still under Q4'25 peak per CFTC.",
      },
      {
        theme: "Rates / term premium",
        direction: "bearish bonds",
        sources: ["Bianco Research", "FRED · DGS30", "Goldman GIR (S)"],
        items: 7, lastUpdate: "07:58",
        synopsis: "TLT failed to reclaim 50DMA; term premium expanding into front-loaded Q3 supply. Bianco the loudest, GS sell-side concurs reluctantly.",
      },
      {
        theme: "AI / tech leadership",
        direction: "mixed",
        sources: ["@woodway", "ZeroHedge RSS"],
        items: 11, lastUpdate: "08:13",
        synopsis: "Twitter/RSS tier is loud but split — NVDA distribution candles vs. AI-capex tape. Low source weight, brain treats as noise.",
      },
    ],
    bySource: [
      { name: "Doomberg", source_id: "doomberg", kind: "Substack", weight: 0.92, freshness: "fresh",
        lastFetch: "08:02", items7d: 6, attrib30d: +6840,
        author: "Doomberg", market_focus: "energy, commodities", research_style: "contrarian",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["substack", "rss"],
        onboarded_at: "2025-11-01",
        latestTitle: "The Uranium Renaissance, Part IV",
        latestSnippet: "Physical U3O8 is firming above $94 as restart cadence accelerates; we lay out the 2026 supply gap and why Cameco's hand-to-mouth contracts are about to bite.",
        themes: ["energy", "uranium"], direction: "bullish" },
      { name: "Energy Capitalist", source_id: "energy_capitalist", kind: "Newsletter", weight: 0.81, freshness: "fresh",
        lastFetch: "08:11", items7d: 4, attrib30d: +3120,
        author: "Josh Young", market_focus: "energy, E&P", research_style: "fundamental",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["email", "rss"],
        onboarded_at: "2025-12-01",
        latestTitle: "Brent reclaims $86 — what comes next",
        latestSnippet: "OVX deflating into the move tells you positioning is light. Capex tape supportive; XLE adv/dec breadth at 28d high.",
        themes: ["energy"], direction: "bullish" },
      { name: "Bianco Research", source_id: "bianco_research", kind: "Substack", weight: 0.68, freshness: "fresh",
        lastFetch: "06:14", items7d: 3, attrib30d: +890,
        author: "Jim Bianco", market_focus: "rates, macro", research_style: "data-driven",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["substack"],
        onboarded_at: "2026-01-10",
        latestTitle: "Term premium and the Q3 supply wall",
        latestSnippet: "Failure of TLT to reclaim 50DMA is consistent with the term-premium expansion we've been calling. Inflation tape is sticky and supply is front-loaded.",
        themes: ["macro", "rates"], direction: "bearish bonds" },
      { name: "Capitalist Exploits", source_id: "capitalist_exploits", kind: "Substack", weight: 0.74, freshness: "fresh",
        lastFetch: "07:56", items7d: 5, attrib30d: +1810,
        author: "Chris MacIntosh", market_focus: "thematic, hard assets", research_style: "thematic",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["substack"],
        onboarded_at: "2026-01-15",
        latestTitle: "Hard assets, soft narratives",
        latestSnippet: "Real assets continue to leak alpha out of the index. Positioning data shows the long-only world still underweight commodity producers vs. 2014 highs.",
        themes: ["thematic", "commodities"], direction: "bullish" },
      { name: "FRED · DGS10", source_id: "fred", kind: "Data feed", weight: 0.78, freshness: "fresh",
        lastFetch: "08:14", items7d: 7, attrib30d: +2470,
        author: "Federal Reserve", market_focus: "rates, macro", research_style: "data",
        fetch_cadence: "daily", freshness_sla_hours: 24, channels: ["api"],
        onboarded_at: "2025-10-01",
        latestTitle: "10Y -8bps, real yields -18bps in 2 sessions",
        latestSnippet: "Move is concentrated at the long end and is reflected in TIPS. Consistent with the macro_alignment scorer's gold + real-asset push.",
        themes: ["macro"], direction: "supportive" },
      { name: "FRED · CPI exp.", source_id: "fred", kind: "Data feed", weight: 0.78, freshness: "fresh",
        lastFetch: "08:14", items7d: 1, attrib30d: +2470,
        author: "Federal Reserve", market_focus: "inflation, macro", research_style: "data",
        fetch_cadence: "daily", freshness_sla_hours: 24, channels: ["api"],
        onboarded_at: "2025-10-01",
        latestTitle: "5Y breakeven holds 2.42%",
        latestSnippet: "Breakeven plateauing but elevated — supports the commodity-led-inflation regime classification.",
        themes: ["macro"], direction: "supportive" },
      { name: "Goldman GIR (S)", source_id: "goldman_gir", kind: "Sell-side", weight: 0.62, freshness: "1d",
        lastFetch: "Yest", items7d: 2, attrib30d: +420,
        author: "Goldman Sachs GIR", market_focus: "equity, sector", research_style: "sell-side",
        fetch_cadence: "as-published", freshness_sla_hours: 72, channels: ["manual"],
        onboarded_at: "2026-02-01",
        latestTitle: "Energy: Constructive on E&P, neutral integrateds",
        latestSnippet: "Selective on energy — likes producers w/ FCF discipline, dislikes the integrated complex. Aligns weakly with the XOP long.",
        themes: ["sell-side"], direction: "constructive" },
      { name: "Forward Guidance", source_id: "forward_guidance", kind: "Podcast (RSS)", weight: 0.61, freshness: "1d",
        lastFetch: "Yest", items7d: 2, attrib30d: +210,
        author: "Jack Farley", market_focus: "macro, rates, credit", research_style: "interview",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["rss", "podcast"],
        onboarded_at: "2026-01-20",
        latestTitle: "Episode 188 · Term premium with G. Boyd",
        latestSnippet: "Term-premium discussion mostly echoes Bianco; one decent point on supply schedule re-accelerating in late Q3.",
        themes: ["macro", "podcast"], direction: "bearish bonds" },
      { name: "Macro Voices", source_id: "macro_voices", kind: "Podcast (RSS)", weight: 0.55, freshness: "stale",
        lastFetch: "2d", items7d: 1, attrib30d: -120,
        author: "Erik Townsend", market_focus: "macro, energy", research_style: "interview",
        fetch_cadence: "weekly", freshness_sla_hours: 168, channels: ["rss", "podcast"],
        onboarded_at: "2026-01-25",
        latestTitle: "Crude special with M. Rocci",
        latestSnippet: "Oil-bull commentary that has not aged well — flagged as low-signal by attribution loop. De-weight 0.05 pending review.",
        themes: ["macro", "podcast"], direction: "bullish" },
      { name: "ZeroHedge RSS", source_id: "zerohedge_rss", kind: "RSS", weight: 0.28, freshness: "fresh",
        lastFetch: "08:10", items7d: 22, attrib30d: -640,
        author: "ZeroHedge", market_focus: "news, geopolitics", research_style: "aggregator",
        fetch_cadence: "hourly", freshness_sla_hours: 4, channels: ["rss"],
        onboarded_at: "2025-10-15",
        latestTitle: "Multiple geopolitical headlines",
        latestSnippet: "High-volume tier, low source weight. Treated as ambient noise unless cross-corroborated by tier-1 sources.",
        themes: ["news"], direction: "mixed" },
      { name: "@woodway", source_id: "woodway_twitter", kind: "Twitter", weight: 0.42, freshness: "fresh",
        lastFetch: "08:13", items7d: 18, attrib30d: -380,
        author: "@woodway", market_focus: "positioning, tech", research_style: "social",
        fetch_cadence: "daily", freshness_sla_hours: 12, channels: ["twitter"],
        onboarded_at: "2026-02-10",
        latestTitle: "AI capex chart series",
        latestSnippet: "Loud but unfocused; AI/NVDA takes are split. Source weight trending down (-0.06 in 30d).",
        themes: ["positioning", "tech"], direction: "mixed" },
    ],
  },

  // Conversion analytics for journal step ⑤ funnel-rail card.
  funnelConversion: {
    marked30d: 14,
    promoted30d: 6,
    activated30d: 4,
    closed30d: 3,
    hitRateBySource: [
      { source: "watchlist_manual", trades: 9, wins: 6, pnlPct: +3.42 },
      { source: "watchlist_auto",   trades: 3, wins: 2, pnlPct: +1.18 },
      { source: "inbox",            trades: 2, wins: 0, pnlPct: -1.94 },
    ],
  },

  // ---------- Asset detail page (design-folder port) ----------
  portfolio: { equityUsd: 612400, cashUsd: 195800 },

  // Macro home dashboard — top assets by category with prices + sentiment.
  // Sentiment: bullish | bearish | neutral. Change fields are day-over-day.
  // Real /api/desk/data will overlay this shape once /api/macro/home lands.
  macroHome: {
    asOf: "2026-08-02 08:14 ET",
    categories: [
      {
        key: "monetary",
        label: "Monetary · liquidity",
        blurb: "Global money supply, dollar, and rates — the macro tape.",
        assets: [
          { asset: "M2SL",     name: "US M2 money supply",   value: 21850, unit: "B",  chgPct: 0.42,  chg30dPct: 1.10,  sentiment: "bullish", note: "expanding at 5.1% YoY · reaccelerating from Feb trough" },
          { asset: "DXY",      name: "US dollar index",      value: 99.20, unit: "",   chgPct: -0.38, chg30dPct: -2.20, sentiment: "bearish", note: "breaking 100 support · confirms liquidity-easing bias" },
          { asset: "US10Y",    name: "10-year Treasury",     value: 4.12,  unit: "%",  chgPct: -0.05, chg30dPct: -0.22, sentiment: "neutral", note: "termite bid range-bound · fiscal supply capped" },
          { asset: "US02Y",    name: "2-year Treasury",      value: 3.68,  unit: "%",  chgPct: -0.03, chg30dPct: -0.35, sentiment: "bullish", note: "front-end pricing 2 cuts by year-end" },
          { asset: "FCI",      name: "Fin. conditions",      value: -0.554, unit: "z", chgPct: -0.02, chg30dPct: -0.19, sentiment: "bullish", note: "easing · below neutral for 42 days" },
          { asset: "MOVE",     name: "Rate vol (MOVE)",      value: 84,    unit: "",   chgPct: -1.6,  chg30dPct: -12.4, sentiment: "bullish", note: "rate vol crushed · fixed-income complex calms" },
        ],
      },
      {
        key: "indices",
        label: "Equity indices",
        blurb: "Broad market breadth, risk-on tape.",
        assets: [
          { asset: "SPX",   name: "S&P 500",             value: 5720,  unit: "",  chgPct: 0.28,  chg30dPct: 3.10,  sentiment: "bullish", note: "grinding higher · above 50/200 DMA · breadth confirming" },
          { asset: "NDX",   name: "Nasdaq 100",          value: 20180, unit: "",  chgPct: 0.44,  chg30dPct: 4.60,  sentiment: "bullish", note: "AI capex leaders leading · MAG7 concentration risk" },
          { asset: "RUT",   name: "Russell 2000",        value: 2210,  unit: "",  chgPct: 0.82,  chg30dPct: 5.10,  sentiment: "bullish", note: "small-cap catch-up · rate-cut beneficiary" },
          { asset: "DJI",   name: "Dow Jones",           value: 42150, unit: "",  chgPct: 0.19,  chg30dPct: 2.40,  sentiment: "bullish", note: "cyclical leadership rotating in" },
          { asset: "VIX",   name: "Volatility (VIX)",    value: 13.2,  unit: "",  chgPct: -3.1,  chg30dPct: -8.5,  sentiment: "bullish", note: "compressed · complacency setting in below 14" },
          { asset: "SPY-BR",name: "SPX breadth (%>200D)", value: 68,   unit: "%", chgPct: 1.2,   chg30dPct: 6.0,   sentiment: "bullish", note: "healthy · not overbought · 70% is the caution flag" },
        ],
      },
      {
        key: "crypto",
        label: "Crypto",
        blurb: "Digital-asset tape · liquidity-sensitive risk lever.",
        assets: [
          { asset: "BTC",   name: "Bitcoin",             value: 71800, unit: "",  chgPct: 1.85,  chg30dPct: 8.20,  sentiment: "bullish", note: "cup+handle breakout retest · spot ETF flows +$1.2B/wk" },
          { asset: "ETH",   name: "Ethereum",            value: 3820,  unit: "",  chgPct: 2.10,  chg30dPct: 6.80,  sentiment: "bullish", note: "reclaiming 3600 · ETF launch adjusting flow pipe" },
          { asset: "SOL",   name: "Solana",              value: 178,   unit: "",  chgPct: 3.40,  chg30dPct: 12.5,  sentiment: "bullish", note: "L1 leader vs ETH · high-beta of the cycle" },
          { asset: "TOTAL", name: "Total crypto mcap",   value: 2.68,  unit: "T", chgPct: 1.95,  chg30dPct: 7.60,  sentiment: "bullish", note: "$2.68T · reclaiming Q1 highs · risk-on confirmed" },
          { asset: "USDT",  name: "Tether supply",       value: 118,   unit: "B", chgPct: 0.20,  chg30dPct: 2.10,  sentiment: "bullish", note: "stablecoin float expanding · net inflow proxy" },
          { asset: "DOMBTC",name: "BTC dominance",       value: 55.4,  unit: "%", chgPct: -0.30, chg30dPct: -1.80, sentiment: "neutral", note: "topping · alt-season signal if breaks 54" },
        ],
      },
      {
        key: "commodities",
        label: "Commodities · hard assets",
        blurb: "Real-asset tape confirming the framework regime.",
        assets: [
          { asset: "GC",    name: "Gold",                value: 2680,  unit: "",  chgPct: 0.65,  chg30dPct: 3.20,  sentiment: "bullish", note: "monetary debasement leader · above 2600 anchor" },
          { asset: "SI",    name: "Silver",              value: 32.40, unit: "",  chgPct: 1.20,  chg30dPct: 5.80,  sentiment: "bullish", note: "gold/silver ratio compressing · industrial demand" },
          { asset: "CL",    name: "WTI crude",           value: 86.20, unit: "",  chgPct: 0.90,  chg30dPct: 4.10,  sentiment: "bullish", note: "OVX deflating · Strait headlines fading" },
          { asset: "HG",    name: "Copper",              value: 4.62,  unit: "",  chgPct: 0.35,  chg30dPct: 2.90,  sentiment: "bullish", note: "supply tightness · China stimulus tailwind" },
          { asset: "U308",  name: "Uranium U3O8",        value: 94.10, unit: "",  chgPct: 1.10,  chg30dPct: 6.40,  sentiment: "bullish", note: "physical firming above $94 · reactor restart cadence" },
          { asset: "DBA",   name: "Agri complex",        value: 26.80, unit: "",  chgPct: 0.40,  chg30dPct: 1.90,  sentiment: "neutral", note: "ag tape firming · watching soybean COT extreme" },
        ],
      },
    ],
  },

  // 90-day daily close price series per asset (most recent last)
  priceSeries: {
    "URA":  [33.20,33.45,33.10,33.80,34.05,34.60,34.40,34.10,34.55,35.10,35.45,35.20,35.80,36.05,35.70,35.40,35.95,36.20,36.50,36.20,35.90,36.40,36.85,37.20,37.05,36.80,37.30,37.65,38.00,38.10,37.85,38.20,38.55,38.80,38.60,38.30,38.65,38.95,39.20,39.05,38.85,39.10,39.40,39.65,39.85,39.60,39.30,39.55,39.85,40.10,40.30,40.05,39.80,40.10,40.40,40.65,40.45,40.20,40.55,40.85,40.60,40.35,40.65,40.95,41.10,40.85,40.55,40.20,39.95,40.25,40.60,40.85,41.05,40.80,40.55,40.85,41.15,41.40,41.20,40.95,41.25,41.45,41.30,41.10,41.35,41.05,40.85,41.10,41.30,41.20],
    "GLD":  [248.40,249.10,248.60,249.30,250.10,250.80,251.20,250.60,251.40,252.30,253.10,252.50,253.40,254.20,254.90,254.30,253.80,254.60,255.40,256.10,255.50,254.80,255.70,256.50,257.30,256.90,256.20,257.10,257.90,258.60,258.10,257.40,258.20,259.00,259.80,260.50,259.90,259.20,260.10,260.90,261.70,262.40,261.80,261.10,262.00,262.80,263.60,264.30,263.70,263.00,263.90,264.80,265.60,266.30,265.70,265.00,265.90,266.80,267.60,267.30,266.50,265.80,266.70,267.40,267.10,266.40,267.30,268.20,268.60,267.90,267.20,267.80,268.50,268.90,268.40,267.70,268.20,268.80,268.40],
    "XOP":  [134.20,135.10,134.60,135.40,136.20,135.80,135.10,135.90,136.70,137.50,137.10,136.40,137.20,138.00,138.80,139.40,138.80,138.10,138.90,139.70,140.50,141.20,140.60,139.90,140.70,141.50,142.30,143.00,142.40,141.70,142.50,143.30,144.10,144.80,144.20,143.50,144.30,145.10,145.90,146.50,145.90,145.20,146.00,146.80,147.60,148.20,147.60,146.90,147.70,148.50,149.30,150.00,149.40,148.70,149.50,150.30,151.10,151.70,151.10,150.40,151.20,152.00,151.50,150.80,151.40,152.10],
    "TLT":  [92.40,92.10,92.60,92.30,91.90,91.50,91.80,92.20,91.70,91.20,90.80,91.10,90.60,90.20,89.80,90.10,89.60,89.20,89.50,89.10,88.70,88.40,88.80,88.30,87.90,88.20,87.80,87.40,87.70,87.30,87.60,87.20,86.80,87.10,86.70,86.40,86.80,86.40,86.10,86.40,86.10,86.50,86.20,86.80,86.50,87.10,86.80,87.20,86.90,87.40,87.10,86.80,87.30,87.00,86.60,86.90,86.50,86.20,86.60,86.30,86.00,86.40,86.10,86.50,86.20,86.40],
    "BTC":  [62100,62800,62400,63200,64100,63600,62900,63800,64700,65500,64900,64300,65100,65900,66700,66200,65500,66300,67100,67900,67400,66700,67500,68300,69100,68600,67900,68700,69500,70300,69800,69100,69900,70700,70200,69500,70300,71100,70600,69900,70700,71400,71800,71200,70500,71300,71800,71200],
  },
};

// Merge baseline into MA_DATA with real-snapshot keys winning.
// When this file loads first and data.js is missing/404 (static
// preview), MA_DATA becomes the full mock. When data.js loads after
// and assigns its own object, that wins per-key; the funnel/streams
// keys it doesn't yet emit still fall through to the mock.
const _existing = window.MA_DATA || {};
window.MA_DATA = Object.assign({}, _MA_MOCK, _existing);
})();
